### ISSUE TITLE
Jump to a certain state

### ISSUE THREAD

**Issue by garlen-javier** [luisoliveiras/scriptable-states#12]
Problem:
Let say I have several states. State1 to State50. Example I want State4 to State10 and State15 to State20 each jump to State50, i'm aware that you can switch state via StateCondition but with that the StateMachine would have a very long list of repetitive conditions for the purpose of jumping to a certain state.

Question:
Is there any method available to jump to a certain state instead of using of using a StateCondition to verify and change state?

**Comment by luisoliveiras** [comment]
I just made a quick solution for that on a separate branch, since I don't know if changing the state from outside the state machine is a good idea. If you want to try it, change the repo link on the package manager to this:

https://github.com/luisoliveiras/scriptable-states.git#feature/direct-transition-to-state

**Comment by garlen-javier** [comment]
You have a point, probably it would be better solution if you can put multiple OriginState? So we can group those States with similar condition that going to a certain state.

**Comment by luisoliveiras** [comment]
Ok, that should be a better sollution for this problem. I'll try it here!

**Comment by luisoliveiras** [comment]
Just sent a new commit, same branch, you can try it on the same link as before. I added a list of states to the transitions, and check if the origin state is in there before trying the condition. It should work as you thought. This is just a draft, I'll make a few tests tomorrow to see if it runs ok for different scenarios. Thank you for this contribution.

**Comment by luisoliveiras** [comment]
I created another branch in which I organize the transitions in the state machine by origin. It should have a better performance since internally I'm using a dictionary to get the possible transitions for that origin. It becomes a bit more organized, but you would still have some repeated transitions. (feature/transitions-as-dictionary)

![image](https://user-images.githubusercontent.com/15316288/154864292-a06edf5d-5d2b-4eed-81d1-d81a1cfc6a57.png)

**Comment by garlen-javier** [comment]
Yeah can still have repetitive, let say in your example you have PlayerNormalState, PlayerRunningState, PlayerRecoveringState all those origin states could go to a certain state like PlayerDieState if a death condition is triggered then I probably still need to repeat those transitions on those three Origins.

**Comment by garlen-javier** [comment]
@luisoliveiras I can't seems to find the _feature/transitions-as-dictionary_ branch, please keep also the direct transition to state function as I know what actually good usage for it, like example in multiplayer games wherein you have to make sure the states are synced between objects and jumping to states could solve it.

**Comment by luisoliveiras** [comment]
The branch _feature/transitions-as-dictionary_ has been merged to develop and I just added the method MoveToState(ScriptableState targetState) so you can jump directly to a specific state. You can target the package to the develop branch to get this changes.
